### ISSUE TITLE
Cannot read properties of undefined (reading 'ContactsApi')

### ISSUE THREAD

**Issue by quintenb** [sendinblue/APIv3-typescript-library#46]
Please help me out. What am I missing? I know the documentation is not correct, so I figured out myself how to set the API key and how to enable types. But for some reason I keep getting this error.

Cannot read properties of undefined (reading 'ContactsApi')

It throws on:

```
let apiInstance = new SibApiV3Sdk.ContactsApi()
```

This is my full code for the nextjs serverless endpoint.

```
import { NextApiRequest, NextApiResponse } from "next"
import SibApiV3Sdk, { HttpError } from "sib-api-v3-typescript"

export default async (req: NextApiRequest, res: NextApiResponse) => {
  try {
    const { SENDINBLUE_API_KEY } = process.env

    if (!SENDINBLUE_API_KEY) throw Error("API Key not set")

    const { email } = req.query

    let apiInstance = new SibApiV3Sdk.ContactsApi()

    apiInstance.setApiKey(SibApiV3Sdk.ContactsApiApiKeys.apiKey, SENDINBLUE_API_KEY)

    let createContact = new SibApiV3Sdk.CreateContact()

    createContact.email = email.toString()
    createContact.listIds = [11]

    const result = await apiInstance.createContact(createContact)

    res.status(result.response.statusCode ?? 200).json(result.body)
  } catch (error) {
    if (error instanceof HttpError) {
      res.status(error.statusCode ?? 500).json(error.body)
    } else if (error instanceof Error) {
      res.status(500).json({ error: { message: error.message, name: error.name } })
    }
  }
}
```

**Comment by Lambtsa** [comment]
Hey! So I just came across your issue because I also had the same. There seems to be quite a lot of errors in the documentation but if you actually import the methods directly you can get it to work. 

`import {
  ContactsApi,
  ContactsApiApiKeys,
  TransactionalEmailsApi,
  TransactionalEmailsApiApiKeys,
} from "@sendinblue/client";
import { EmailClient } from "@types";

import { initialiseConfig } from "./config";

const config = initialiseConfig();

const contactsApiInstance = new ContactsApi();
const transactionApiInstance = new TransactionalEmailsApi();
`
Hope this will help you move forward ;)

**Comment by eakl** [comment]
This also solve the issue

```diff
- import SibApi from '@sendinblue/client'
+ import * as SibApi from '@sendinblue/client'
```

**Comment by aayush-sib** [comment]
Hi
We will try to improve our docs, sorry for the inconvenience.
